#!/bin/sh
set -e

case "$1" in
    configure|triggered)
        if which systemctl >/dev/null 2>&1
        then
            systemctl enable hamonikr-usb-persistent.service
            systemctl daemon-reload || true
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
